In [155]:
import pandas as pd

In [156]:
import numpy as np

In [157]:
current_airtable = pd.read_csv('C:\\Users\\Caitlin.Jette\\Documents\\GitHub\\VIEW-site\\Vehicles-Website View.csv')
current_airtable

,ID,Agency,Percent Visible Volume,Percent Visible Volume in Front,Percent Visible Volume in Passenger Side,Make,Model,Year,Body Class,Weight Class,...,Front Vis Elem,Side Vis Elem,Overall Vis Adult,Front Vis Adult,Side Vis Adult,Manually Entered Body Class?,A Pillar Width,Forward Five Star Rating,Passenger Side Five Star Rating,new row
0,1084,NaN,69,80.0,83.0,VOLVO,XC60,2023.0,Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,Class 1,...,47.0,59.0,61.0,70.0,74.0,NaN,13.0,4.0,2,NaN
1,1083,NaN,71,77.0,82.0,FORD,F-750,2019.0,Truck,Class 8,...,48.0,68.0,55.0,57.0,74.0,NaN,9.0,4.0,2,NaN
2,1082,NaN,55,58.0,76.0,FORD,F-150,2021.0,Pickup,Class 2,...,6.0,28.0,26.0,24.0,49.0,NaN,12.0,5.0,3,NaN
3,1081,NaN,62,70.0,76.0,FORD,F-150,2021.0,Pickup,Class 2,...,20.0,48.0,43.0,47.0,59.0,NaN,20.0,5.0,3,NaN
4,1080,NaN,61,69.0,74.0,FORD,F-150,2021.0,Pickup,Class 2,...,19.0,46.0,42.0,46.0,57.0,NaN,2.0,5.0,3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,1,NaN,78,NaN,NaN,ISUZU,NPR,NaN,Truck,Class 4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,NaN
447,2,NaN,63,NaN,NaN,FORD,F-350,NaN,Pickup,Class 3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,NaN
448,3,NaN,59,NaN,NaN,FREIGHTLINER,108SD,NaN,Truck,Class 8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,NaN
449,5,NaN,72,NaN,NaN,MACK,MRU,NaN,Truck,Class 8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,NaN
450,6,NaN,65,NaN,NaN,PETERBILT,348,NaN,Truck,Class 8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,NaN

In [158]:
current_airtable.shape

(451, 54)

In [159]:
current_airtable = current_airtable.fillna({
    'Passenger Side Five Star Rating': 0, 
    'Forward Five Star Rating': 0,
    'Overall Vis Adult':0,
    'Front Vis Elem':0,
    'Side Vis Elem':0,
    'Front Vis Adult':0,
    'Side Vis Adult':0,
    'Overall Vis Elem':0,
    'new row':0
})
current_airtable

,ID,Agency,Percent Visible Volume,Percent Visible Volume in Front,Percent Visible Volume in Passenger Side,Make,Model,Year,Body Class,Weight Class,...,Front Vis Elem,Side Vis Elem,Overall Vis Adult,Front Vis Adult,Side Vis Adult,Manually Entered Body Class?,A Pillar Width,Forward Five Star Rating,Passenger Side Five Star Rating,new row
0,1084,NaN,69,80.0,83.0,VOLVO,XC60,2023.0,Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,Class 1,...,47.0,59.0,61.0,70.0,74.0,NaN,13.0,4.0,2,0.0
1,1083,NaN,71,77.0,82.0,FORD,F-750,2019.0,Truck,Class 8,...,48.0,68.0,55.0,57.0,74.0,NaN,9.0,4.0,2,0.0
2,1082,NaN,55,58.0,76.0,FORD,F-150,2021.0,Pickup,Class 2,...,6.0,28.0,26.0,24.0,49.0,NaN,12.0,5.0,3,0.0
3,1081,NaN,62,70.0,76.0,FORD,F-150,2021.0,Pickup,Class 2,...,20.0,48.0,43.0,47.0,59.0,NaN,20.0,5.0,3,0.0
4,1080,NaN,61,69.0,74.0,FORD,F-150,2021.0,Pickup,Class 2,...,19.0,46.0,42.0,46.0,57.0,NaN,2.0,5.0,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,1,NaN,78,NaN,NaN,ISUZU,NPR,NaN,Truck,Class 4,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
447,2,NaN,63,NaN,NaN,FORD,F-350,NaN,Pickup,Class 3,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
448,3,NaN,59,NaN,NaN,FREIGHTLINER,108SD,NaN,Truck,Class 8,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
449,5,NaN,72,NaN,NaN,MACK,MRU,NaN,Truck,Class 8,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
450,6,NaN,65,NaN,NaN,PETERBILT,348,NaN,Truck,Class 8,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0

In [160]:
for i in current_airtable['Passenger Side Five Star Rating']:
    if current_airtable['Side Vis Adult'][i] and current_airtable['Side Vis Elem'][i] < 36.0:
        current_airtable['Passenger Side Five Star Rating'][i] ==  5.0
    elif current_airtable['Side Vis Adult'][i] < 36.0: 
        current_airtable['Passenger Side Five Star Rating'][i] ==  4.0
    elif current_airtable['Side Vis Adult'][i] < 72.0: 
        current_airtable['Passenger Side Five Star Rating'][i] ==  3.0
    elif current_airtable['Side Vis Adult'][i] < 96.0: 
        current_airtable['Passenger Side Five Star Rating'][i] ==  2.0
    else: 
        current_airtable['Passenger Side Five Star Rating'][i] ==  1.0
current_airtable

,ID,Agency,Percent Visible Volume,Percent Visible Volume in Front,Percent Visible Volume in Passenger Side,Make,Model,Year,Body Class,Weight Class,...,Front Vis Elem,Side Vis Elem,Overall Vis Adult,Front Vis Adult,Side Vis Adult,Manually Entered Body Class?,A Pillar Width,Forward Five Star Rating,Passenger Side Five Star Rating,new row
0,1084,NaN,69,80.0,83.0,VOLVO,XC60,2023.0,Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,Class 1,...,47.0,59.0,61.0,70.0,74.0,NaN,13.0,4.0,2,0.0
1,1083,NaN,71,77.0,82.0,FORD,F-750,2019.0,Truck,Class 8,...,48.0,68.0,55.0,57.0,74.0,NaN,9.0,4.0,2,0.0
2,1082,NaN,55,58.0,76.0,FORD,F-150,2021.0,Pickup,Class 2,...,6.0,28.0,26.0,24.0,49.0,NaN,12.0,5.0,3,0.0
3,1081,NaN,62,70.0,76.0,FORD,F-150,2021.0,Pickup,Class 2,...,20.0,48.0,43.0,47.0,59.0,NaN,20.0,5.0,3,0.0
4,1080,NaN,61,69.0,74.0,FORD,F-150,2021.0,Pickup,Class 2,...,19.0,46.0,42.0,46.0,57.0,NaN,2.0,5.0,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,1,NaN,78,NaN,NaN,ISUZU,NPR,NaN,Truck,Class 4,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
447,2,NaN,63,NaN,NaN,FORD,F-350,NaN,Pickup,Class 3,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
448,3,NaN,59,NaN,NaN,FREIGHTLINER,108SD,NaN,Truck,Class 8,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
449,5,NaN,72,NaN,NaN,MACK,MRU,NaN,Truck,Class 8,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
450,6,NaN,65,NaN,NaN,PETERBILT,348,NaN,Truck,Class 8,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0

In [161]:
current_airtable

,ID,Agency,Percent Visible Volume,Percent Visible Volume in Front,Percent Visible Volume in Passenger Side,Make,Model,Year,Body Class,Weight Class,...,Front Vis Elem,Side Vis Elem,Overall Vis Adult,Front Vis Adult,Side Vis Adult,Manually Entered Body Class?,A Pillar Width,Forward Five Star Rating,Passenger Side Five Star Rating,new row
0,1084,NaN,69,80.0,83.0,VOLVO,XC60,2023.0,Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,Class 1,...,47.0,59.0,61.0,70.0,74.0,NaN,13.0,4.0,2,0.0
1,1083,NaN,71,77.0,82.0,FORD,F-750,2019.0,Truck,Class 8,...,48.0,68.0,55.0,57.0,74.0,NaN,9.0,4.0,2,0.0
2,1082,NaN,55,58.0,76.0,FORD,F-150,2021.0,Pickup,Class 2,...,6.0,28.0,26.0,24.0,49.0,NaN,12.0,5.0,3,0.0
3,1081,NaN,62,70.0,76.0,FORD,F-150,2021.0,Pickup,Class 2,...,20.0,48.0,43.0,47.0,59.0,NaN,20.0,5.0,3,0.0
4,1080,NaN,61,69.0,74.0,FORD,F-150,2021.0,Pickup,Class 2,...,19.0,46.0,42.0,46.0,57.0,NaN,2.0,5.0,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,1,NaN,78,NaN,NaN,ISUZU,NPR,NaN,Truck,Class 4,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
447,2,NaN,63,NaN,NaN,FORD,F-350,NaN,Pickup,Class 3,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
448,3,NaN,59,NaN,NaN,FREIGHTLINER,108SD,NaN,Truck,Class 8,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
449,5,NaN,72,NaN,NaN,MACK,MRU,NaN,Truck,Class 8,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
450,6,NaN,65,NaN,NaN,PETERBILT,348,NaN,Truck,Class 8,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0

current_airtable['Passenger Side Five Star Rating']

In [162]:
current_airtable

,ID,Agency,Percent Visible Volume,Percent Visible Volume in Front,Percent Visible Volume in Passenger Side,Make,Model,Year,Body Class,Weight Class,...,Front Vis Elem,Side Vis Elem,Overall Vis Adult,Front Vis Adult,Side Vis Adult,Manually Entered Body Class?,A Pillar Width,Forward Five Star Rating,Passenger Side Five Star Rating,new row
0,1084,NaN,69,80.0,83.0,VOLVO,XC60,2023.0,Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,Class 1,...,47.0,59.0,61.0,70.0,74.0,NaN,13.0,4.0,2,0.0
1,1083,NaN,71,77.0,82.0,FORD,F-750,2019.0,Truck,Class 8,...,48.0,68.0,55.0,57.0,74.0,NaN,9.0,4.0,2,0.0
2,1082,NaN,55,58.0,76.0,FORD,F-150,2021.0,Pickup,Class 2,...,6.0,28.0,26.0,24.0,49.0,NaN,12.0,5.0,3,0.0
3,1081,NaN,62,70.0,76.0,FORD,F-150,2021.0,Pickup,Class 2,...,20.0,48.0,43.0,47.0,59.0,NaN,20.0,5.0,3,0.0
4,1080,NaN,61,69.0,74.0,FORD,F-150,2021.0,Pickup,Class 2,...,19.0,46.0,42.0,46.0,57.0,NaN,2.0,5.0,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,1,NaN,78,NaN,NaN,ISUZU,NPR,NaN,Truck,Class 4,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
447,2,NaN,63,NaN,NaN,FORD,F-350,NaN,Pickup,Class 3,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
448,3,NaN,59,NaN,NaN,FREIGHTLINER,108SD,NaN,Truck,Class 8,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
449,5,NaN,72,NaN,NaN,MACK,MRU,NaN,Truck,Class 8,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
450,6,NaN,65,NaN,NaN,PETERBILT,348,NaN,Truck,Class 8,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0


current_airtable['Passenger Side Five Star Rating'] = np.where(current_airtable['Passenger Side Five Star Rating'] > 20000, 0, df.my_channel)

In [163]:
current_airtable['Passenger Side Five Star Rating'].astype(np.float64)

0      2.0
1      2.0
2      3.0
3      3.0
4      3.0
      ...
446    0.0
447    0.0
448    0.0
449    0.0
450    0.0
Name: Passenger Side Five Star Rating, Length: 451, dtype: float64

In [164]:
current_airtable['Overall Vis Adult'].astype(np.float64)
current_airtable['Front Vis Adult'].astype(np.float64)
current_airtable['Side Vis Adult'].astype(np.float64)
current_airtable['Overall Vis Elem'].astype(np.float64)
current_airtable['Front Vis Elem'].astype(np.float64)
current_airtable['Side Vis Elem'].astype(np.float64)

0      59.0
1      68.0
2      28.0
3      48.0
4      46.0
       ...
446     0.0
447     0.0
448     0.0
449     0.0
450     0.0
Name: Side Vis Elem, Length: 451, dtype: float64

In [165]:
from pandas import Series, DataFrame

In [166]:
current_airtable

,ID,Agency,Percent Visible Volume,Percent Visible Volume in Front,Percent Visible Volume in Passenger Side,Make,Model,Year,Body Class,Weight Class,...,Front Vis Elem,Side Vis Elem,Overall Vis Adult,Front Vis Adult,Side Vis Adult,Manually Entered Body Class?,A Pillar Width,Forward Five Star Rating,Passenger Side Five Star Rating,new row
0,1084,NaN,69,80.0,83.0,VOLVO,XC60,2023.0,Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,Class 1,...,47.0,59.0,61.0,70.0,74.0,NaN,13.0,4.0,2,0.0
1,1083,NaN,71,77.0,82.0,FORD,F-750,2019.0,Truck,Class 8,...,48.0,68.0,55.0,57.0,74.0,NaN,9.0,4.0,2,0.0
2,1082,NaN,55,58.0,76.0,FORD,F-150,2021.0,Pickup,Class 2,...,6.0,28.0,26.0,24.0,49.0,NaN,12.0,5.0,3,0.0
3,1081,NaN,62,70.0,76.0,FORD,F-150,2021.0,Pickup,Class 2,...,20.0,48.0,43.0,47.0,59.0,NaN,20.0,5.0,3,0.0
4,1080,NaN,61,69.0,74.0,FORD,F-150,2021.0,Pickup,Class 2,...,19.0,46.0,42.0,46.0,57.0,NaN,2.0,5.0,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,1,NaN,78,NaN,NaN,ISUZU,NPR,NaN,Truck,Class 4,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
447,2,NaN,63,NaN,NaN,FORD,F-350,NaN,Pickup,Class 3,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
448,3,NaN,59,NaN,NaN,FREIGHTLINER,108SD,NaN,Truck,Class 8,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
449,5,NaN,72,NaN,NaN,MACK,MRU,NaN,Truck,Class 8,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
450,6,NaN,65,NaN,NaN,PETERBILT,348,NaN,Truck,Class 8,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0

In [167]:
df = current_airtable

In [168]:
df

,ID,Agency,Percent Visible Volume,Percent Visible Volume in Front,Percent Visible Volume in Passenger Side,Make,Model,Year,Body Class,Weight Class,...,Front Vis Elem,Side Vis Elem,Overall Vis Adult,Front Vis Adult,Side Vis Adult,Manually Entered Body Class?,A Pillar Width,Forward Five Star Rating,Passenger Side Five Star Rating,new row
0,1084,NaN,69,80.0,83.0,VOLVO,XC60,2023.0,Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,Class 1,...,47.0,59.0,61.0,70.0,74.0,NaN,13.0,4.0,2,0.0
1,1083,NaN,71,77.0,82.0,FORD,F-750,2019.0,Truck,Class 8,...,48.0,68.0,55.0,57.0,74.0,NaN,9.0,4.0,2,0.0
2,1082,NaN,55,58.0,76.0,FORD,F-150,2021.0,Pickup,Class 2,...,6.0,28.0,26.0,24.0,49.0,NaN,12.0,5.0,3,0.0
3,1081,NaN,62,70.0,76.0,FORD,F-150,2021.0,Pickup,Class 2,...,20.0,48.0,43.0,47.0,59.0,NaN,20.0,5.0,3,0.0
4,1080,NaN,61,69.0,74.0,FORD,F-150,2021.0,Pickup,Class 2,...,19.0,46.0,42.0,46.0,57.0,NaN,2.0,5.0,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,1,NaN,78,NaN,NaN,ISUZU,NPR,NaN,Truck,Class 4,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
447,2,NaN,63,NaN,NaN,FORD,F-350,NaN,Pickup,Class 3,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
448,3,NaN,59,NaN,NaN,FREIGHTLINER,108SD,NaN,Truck,Class 8,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
449,5,NaN,72,NaN,NaN,MACK,MRU,NaN,Truck,Class 8,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0
450,6,NaN,65,NaN,NaN,PETERBILT,348,NaN,Truck,Class 8,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0,0.0

In [169]:
df.shape

(451, 54)

In [170]:
df.info(memory_usage = 'deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 451 entries, 0 to 450
Data columns (total 54 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   ID                                                          451 non-null    int64
 1   Agency                                                      170 non-null    object
 2   Percent Visible Volume                                      451 non-null    int64
 3   Percent Visible Volume in Front                             419 non-null    float64
 4   Percent Visible Volume in Passenger Side                    419 non-null    float64
 5   Make                                                        451 non-null    object
 6   Model                                                       445 non-null    object
 7   Year                                                        446 non-null    float64
 8   Body Class                                                  450 non-null    object
 9   Weight Class                                                371 non-null    object
 10  Full VIN                                                    368 non-null    object
 11  Image                                                       317 non-null    object
 12  Drawing                                                     341 non-null    object
 13  Time Added                                                  451 non-null    object
 14  a                                                           446 non-null    float64
 15  Partial VIN                                                 368 non-null    object
 16  when                                                        5 non-null      object
 17  b                                                           446 non-null    float64
 18  c                                                           446 non-null    float64
 19  d                                                           446 non-null    float64
 20  Comments                                                    239 non-null    object
 21  Preschool Children in Blindzone                             441 non-null    float64
 22  Grade School Children in Blindzone                          446 non-null    float64
 23  Adults in Blindzone                                         446 non-null    float64
 24  Wheelchair Users in Blindzone                               446 non-null    float64
 25  Bicyclists in Blindzone                                     446 non-null    float64
 26  Grade School Child Bicyclists in Blindzone                  446 non-null    float64
 27  Total Front Volume                                          419 non-null    float64
 28  Total Passenger Volume                                      419 non-null    float64
 29  Total A Pillar Volume                                       419 non-null    float64
 30  Image URL                                                   338 non-null    object
 31  Percent Visible Volume (Metric Standard)                    381 non-null    float64
 32  Percent Visible Volume in Front (Metric Standard)           381 non-null    float64
 33  Percent Visible Volume in Passenger Side (Metric Standard)  381 non-null    float64
 34  a (cm)                                                      446 non-null    float64
 35  b (cm)                                                      446 non-null    float64
 36  c (cm)                                                      446 non-null    float64
 37  d (cm)                                                      446 non-null    float64
 38  Phis and NVPS json                                          377 non-null    object
 39  Front Image String                                          407 non-null    object
 40  Side Image String                                           339 non-null    object
 41  Overhead Image String                                       310 non-null    object
 42  Date Added                                                  451 non-null    object
 43  Overall Vis Elem                                            451 non-null    float64
 44  Front Vis Elem                                              451 non-null    float64
 45  Side Vis Elem                                               451 non-null    float64
 46  Overall Vis Adult                                           451 non-null    float64
 47  Front Vis Adult                                             451 non-null    float64
 48  Side Vis Adult                                              451 non-null    float64
 49  Manually Entered Body Class?                                46 non-null     object
 50  A Pillar Width                                              6 non-null      float64
 51  Forward Five Star Rating                                    451 non-null    float64
 52  Passenger Side Five Star Rating                             451 non-null    int64
 53  new row                                                     451 non-null    float64
dtypes: float64(32), int64(3), object(19)
memory usage: 1.9 MB

In [171]:
df.columns

Index(['ID', 'Agency', 'Percent Visible Volume',
       'Percent Visible Volume in Front',
       'Percent Visible Volume in Passenger Side', 'Make', 'Model', 'Year',
       'Body Class', 'Weight Class', 'Full VIN', 'Image', 'Drawing',
       'Time Added', 'a', 'Partial VIN', 'when', 'b', 'c', 'd', 'Comments',
       'Preschool Children in Blindzone', 'Grade School Children in Blindzone',
       'Adults in Blindzone', 'Wheelchair Users in Blindzone',
       'Bicyclists in Blindzone', 'Grade School Child Bicyclists in Blindzone',
       'Total Front Volume', 'Total Passenger Volume', 'Total A Pillar Volume',
       'Image URL', 'Percent Visible Volume (Metric Standard)',
       'Percent Visible Volume in Front (Metric Standard)',
       'Percent Visible Volume in Passenger Side (Metric Standard)', 'a (cm)',
       'b (cm)', 'c (cm)', 'd (cm)', 'Phis and NVPS json',
       'Front Image String', 'Side Image String', 'Overhead Image String',
       'Date Added', 'Overall Vis Elem', 'Front Vis Elem', 'Side Vis Elem',
       'Overall Vis Adult', 'Front Vis Adult', 'Side Vis Adult',
       'Manually Entered Body Class?', 'A Pillar Width',
       'Forward Five Star Rating', 'Passenger Side Five Star Rating',
       'new row'],
      dtype='object')

In [172]:
df = pd.read_csv(filename, 
                usecols= ['Front Vis Adult', 'Side Vis Adult', 'Front Vis Elem', 'Side Vis Elem', 'Passenger Side Five Star Rating', 'Forward Five Star Rating', 'A Pillar Width', 'new row'])

In [173]:
filename = 'C:\\Users\\Caitlin.Jette\\Documents\\GitHub\\VIEW-site\\Vehicles-Website View.csv'

In [174]:
df.shape

(451, 8)

In [175]:
old_column_names = Series(['ID', 'Agency', 'Percent Visible Volume',
       'Percent Visible Volume in Front',
       'Percent Visible Volume in Passenger Side', 'Make', 'Model', 'Year',
       'Body Class', 'Weight Class', 'Full VIN', 'Image', 'Drawing',
       'Time Added', 'a', 'Partial VIN', 'when', 'b', 'c', 'd', 'Comments',
       'Preschool Children in Blindzone', 'Grade School Children in Blindzone',
       'Adults in Blindzone', 'Wheelchair Users in Blindzone',
       'Bicyclists in Blindzone', 'Grade School Child Bicyclists in Blindzone',
       'Total Front Volume', 'Total Passenger Volume', 'Total A Pillar Volume',
       'Image URL', 'Percent Visible Volume (Metric Standard)',
       'Percent Visible Volume in Front (Metric Standard)',
       'Percent Visible Volume in Passenger Side (Metric Standard)', 'a (cm)',
       'b (cm)', 'c (cm)', 'd (cm)', 'Phis and NVPS json',
       'Front Image String', 'Side Image String', 'Overhead Image String',
       'Date Added', 'Overall Vis Elem', 'Front Vis Elem', 'Side Vis Elem',
       'Overall Vis Adult', 'Front Vis Adult', 'Side Vis Adult',
       'Manually Entered Body Class?', 'A Pillar Width',
       'Forward Five Star Rating', 'Passenger Side Five Star Rating', 'new row'])

In [176]:
old_column_names

0                                                    ID
1                                                Agency
2                                Percent Visible Volume
3                       Percent Visible Volume in Front
4              Percent Visible Volume in Passenger Side
5                                                  Make
6                                                 Model
7                                                  Year
8                                            Body Class
9                                          Weight Class
10                                             Full VIN
11                                                Image
12                                              Drawing
13                                           Time Added
14                                                    a
15                                          Partial VIN
16                                                 when
17                                                    b
18                                                    c
19                                                    d
20                                             Comments
21                      Preschool Children in Blindzone
22                   Grade School Children in Blindzone
23                                  Adults in Blindzone
24                        Wheelchair Users in Blindzone
25                              Bicyclists in Blindzone
26           Grade School Child Bicyclists in Blindzone
27                                   Total Front Volume
28                               Total Passenger Volume
29                                Total A Pillar Volume
30                                            Image URL
31             Percent Visible Volume (Metric Standard)
32    Percent Visible Volume in Front (Metric Standard)
33    Percent Visible Volume in Passenger Side (Metr...
34                                               a (cm)
35                                               b (cm)
36                                               c (cm)
37                                               d (cm)
38                                   Phis and NVPS json
39                                   Front Image String
40                                    Side Image String
41                                Overhead Image String
42                                           Date Added
43                                     Overall Vis Elem
44                                       Front Vis Elem
45                                        Side Vis Elem
46                                    Overall Vis Adult
47                                      Front Vis Adult
48                                       Side Vis Adult
49                         Manually Entered Body Class?
50                                       A Pillar Width
51                             Forward Five Star Rating
52                      Passenger Side Five Star Rating
53                                              new row
dtype: object

In [177]:
df = pd.read_csv(filename, usecols= [44,45,46,47,48,50,51,52, 53])
df

,Front Vis Elem,Side Vis Elem,Overall Vis Adult,Front Vis Adult,Side Vis Adult,A Pillar Width,Forward Five Star Rating,Passenger Side Five Star Rating,new row
0,47.0,59.0,61.0,70.0,74.0,13.0,4.0,2,NaN
1,48.0,68.0,55.0,57.0,74.0,9.0,4.0,2,NaN
2,6.0,28.0,26.0,24.0,49.0,12.0,5.0,3,NaN
3,20.0,48.0,43.0,47.0,59.0,20.0,5.0,3,NaN
4,19.0,46.0,42.0,46.0,57.0,2.0,5.0,3,NaN
...,...,...,...,...,...,...,...,...,...
446,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,NaN
447,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,NaN
448,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,NaN
449,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,NaN
450,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,NaN

In [178]:
import numpy as np
import pandas as pd
from pandas import DataFrame

In [179]:
df.fillna(0)
df = df.astype({'Passenger Side Five Star Rating': 'int'})

In [180]:
df = df.fillna(0)

In [181]:
df
df = df.astype({'A Pillar Width': 'int'})

In [182]:
df = df.astype({'Passenger Side Five Star Rating': 'int'})
df

,Front Vis Elem,Side Vis Elem,Overall Vis Adult,Front Vis Adult,Side Vis Adult,A Pillar Width,Forward Five Star Rating,Passenger Side Five Star Rating,new row
0,47.0,59.0,61.0,70.0,74.0,13,4.0,2,0.0
1,48.0,68.0,55.0,57.0,74.0,9,4.0,2,0.0
2,6.0,28.0,26.0,24.0,49.0,12,5.0,3,0.0
3,20.0,48.0,43.0,47.0,59.0,20,5.0,3,0.0
4,19.0,46.0,42.0,46.0,57.0,2,5.0,3,0.0
...,...,...,...,...,...,...,...,...,...
446,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.0
447,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.0
448,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.0
449,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.0
450,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.0

In [183]:
df

,Front Vis Elem,Side Vis Elem,Overall Vis Adult,Front Vis Adult,Side Vis Adult,A Pillar Width,Forward Five Star Rating,Passenger Side Five Star Rating,new row
0,47.0,59.0,61.0,70.0,74.0,13,4.0,2,0.0
1,48.0,68.0,55.0,57.0,74.0,9,4.0,2,0.0
2,6.0,28.0,26.0,24.0,49.0,12,5.0,3,0.0
3,20.0,48.0,43.0,47.0,59.0,20,5.0,3,0.0
4,19.0,46.0,42.0,46.0,57.0,2,5.0,3,0.0
...,...,...,...,...,...,...,...,...,...
446,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.0
447,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.0
448,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.0
449,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.0
450,0.0,0.0,0.0,0.0,0.0,0,0.0,0,0.0

In [184]:
df = df.astype({'Passenger Side Five Star Rating': 'int', 'Front Vis Elem': 'int', 'Side Vis Elem': 'int', 'Overall Vis Adult': 'int', 'Front Vis Adult': 'int', 'Side Vis Adult': 'int', 'A Pillar Width': 'int', 'Forward Five Star Rating': 'int', 'new row': 'int'})

In [185]:
df.loc[(df['Side Vis Adult'] < 36) & (df['Side Vis Elem'] < 36), 'Passenger'] = 5
df.loc[(df['Side Vis Adult'] < 36) & (df['Side Vis Elem'] >= 36), 'Passenger'] = 4
df.loc[(df['Side Vis Adult'] < 72) & (df['Side Vis Adult'] >= 36),'Passenger'] = 3 
df.loc[(df['Side Vis Adult'] < 96) & (df['Side Vis Adult'] >= 72), 'Passenger'] = 2 
df.loc[(df['Side Vis Adult'] >= 96), 'Passenger'] = 1 
df.loc[(df['Side Vis Adult'] == 0), 'Passenger'] = 0

df.loc[(df['Front Vis Elem'] < 48) & (df['Front Vis Adult'] < 48), 'Forward'] = 5
df.loc[(df['Front Vis Elem'] < 72) & (df['Front Vis Adult'] >= 48), 'Forward'] = 4
df.loc[(df['Front Vis Elem'] < 96) & (df['Front Vis Elem'] >= 72),'Forward'] = 3 
df.loc[(df['Front Vis Elem'] < 120) & (df['Front Vis Elem'] >= 96), 'Forward'] = 2 
df.loc[(df['Front Vis Elem'] >= 120), 'Forward'] = 1 
df.loc[(df['Front Vis Elem'] == 0), 'Forward'] = 0

In [186]:
df

,Front Vis Elem,Side Vis Elem,Overall Vis Adult,Front Vis Adult,Side Vis Adult,A Pillar Width,Forward Five Star Rating,Passenger Side Five Star Rating,new row,Passenger,Forward
0,47,59,61,70,74,13,4,2,0,2.0,4.0
1,48,68,55,57,74,9,4,2,0,2.0,4.0
2,6,28,26,24,49,12,5,3,0,3.0,5.0
3,20,48,43,47,59,20,5,3,0,3.0,5.0
4,19,46,42,46,57,2,5,3,0,3.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...
446,0,0,0,0,0,0,0,0,0,0.0,0.0
447,0,0,0,0,0,0,0,0,0,0.0,0.0
448,0,0,0,0,0,0,0,0,0,0.0,0.0
449,0,0,0,0,0,0,0,0,0,0.0,0.0
450,0,0,0,0,0,0,0,0,0,0.0,0.0

In [187]:
df.to_clipboard()

In [188]:
df = pd.read_csv(filename, usecols= [38, 53])
df

                                    Phis and NVPS json  new row
0    {"phis":[-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,...      NaN
1    {"phis":[-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-...      NaN
2    {"phis":[-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-...      NaN
3    {"phis":[-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,...      NaN
4    {"phis":[-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,...      NaN
..                                                 ...      ...
446                                                NaN      NaN
447                                                NaN      NaN
448                                                NaN      NaN
449                                                NaN      NaN
450                                                NaN      NaN

[451 rows x 2 columns]

In [200]:
df.fillna(0)
import json
for i in range(df['Phis and NVPS json'].shape[0]):
    original_string = df['Phis and NVPS json'][i]
    result = json.loads(original_string)
    nvps = result['nvps']
    #df['new row'][i] = nvps

KeyError: 'nvps'

In [195]:
import json
original_string = df['Phis and NVPS json'][2]
result = json.loads(original_string)
#print(str(result))
#result.keys()
#print(result['nvps'])
nvps = result['nvps']
print(nvps)

df.loc[(result := json.loads(df['Phis and NVPS json'])), (nvps := result['NVPS']), 'new row'] = nvps

for

[279, 280, 280, 283, 285, 284, 283, 283, 283, 285, 285, 285, 282, 279, 277, 268, 265, 264, 261, 258, 253, 249, 244, 240, 240, 241, 247, 252, 386, 608, 608, 608, 608, 608, 599, 596, 596, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 523, 523, 529, 533, 533, 533, 533, 533, 545, 558, 567, 584, 584, 584, 584, 584, 584, 602, 627, 633, 627, 608, 584, 584, 584, 584, 584, 584, 584, 584, 584, 584, 584, 581, 564, 552, 552, 552, 552, 552, 552, 559, 562, 562, 573, 584, 584, 584, 584, 584, 573, 570, 562, 562, 573, 584, 587, 596, 591, 584, 570, 562, 553, 552, 548, 527, 515, 496, 482, 482, 492, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633, 633]

TypeError: the JSON object must be str, bytes or bytearray, not Series

In [191]:



#import json
#for i in df['Phis and NVPS json']:
    #original_string = df['Phis and NVPS json'][i]
    #result = json.loads(original_string)
    #print(str(result))
    #result.keys()

In [192]:
nvps.max()

AttributeError: 'list' object has no attribute 'max'

In [109]:
m

TypeError: 'int' object is not callable